### PR TITLE
Add support to download all EEGEyeNet DOTS data.

### PR DESCRIPTION
**Pull request by christian-oreilly**
Add the ability to download EEGEyeNet data for any subject/run for the DOTS protocol.

### CODE REVIEW

**Comment by scott-huberty** [comment]
Errors seem unrelated. Fine with me if you merge and I'll circle back on this

**Comment by scott-huberty** [comment]
Per Discord discussion, we probably need to bump python version to 3.9:

https://github.com/lina-usc/eog-learn/blob/11de755770089d18445e3edd114e20c7327b5be1/pyproject.toml#L11

**Comment by christian-oreilly** [comment]
Yeah, I think `tensorflow-cpu` just does not work with macos arm64. Looks like it would be more `tensorflow-macos tensorflow-metal` in this case. Not sure about the proper way to deal with these system specific dependencies in the setup

**Comment by scott-huberty** [comment]
> Yeah, I think `tensorflow-cpu` just does not work with macos arm64. Looks like it would be more `tensorflow-macos tensorflow-metal` in this case. Not sure about the proper way to deal with these system specific dependencies in the setup

arg that's Probably right.. Well you're right that the CI is probably over kill right now anyways. If we end up sticking with TF we could just install Tensorflow (I was using the CPU version during dev because the install size was smaller).

**Comment by scott-huberty** [comment]
And thanks for looking into that.

**Comment by christian-oreilly** [comment]
OK. I removed that dependencies for macos specifically for now. Install for macos in CI is working now.

**Comment by christian-oreilly** [comment]
@scott-huberty CI works now for macos. I had to comment two asserts https://github.com/lina-usc/eog-learn/blob/40cdbb47c3aed4d073ade6244c2249de4fd5e143/eoglearn/models/tests/test_models.py#L31-L32 because, in the CI test, the property input_shape did not exist at that point for the LSTM object. The same test worked locally. I think that depending on the platform (and probably CPU vs GPU; I removed the tensorflow-cpu import for macos), this property may not be instantiated yet when we reach this point.

**Pull request merged**
